import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ScheduleCSummary } from './deductionCalculator';

export async function generateScheduleCPDF(
    summary: ScheduleCSummary,
    year: number,
    user: { name: string; businessName?: string; taxId?: string }
): Promise<Blob> {
    const doc = new jsPDF();

    // -- Header --
    doc.setFontSize(16);
    doc.text('SCHEDULE C (Form 1040)', 14, 20);
    doc.setFontSize(12);
    doc.text('Profit or Loss From Business', 14, 28);
    doc.setFontSize(10);
    doc.text(`Tax Year: ${year}`, 14, 34);

    // -- Business Info --
    doc.setLineWidth(0.5);
    doc.line(14, 38, 196, 38);

    doc.text(`Name of Proprietor: ${user.name}`, 14, 45);
    doc.text(`Business Name: ${user.businessName || 'Self-Employed'}`, 14, 51);
    if (user.taxId) {
        doc.text(`Tax ID (SSN/EIN): ${user.taxId}`, 14, 57);
    }

    // -- Part I: Income --
    doc.setFontSize(12);
    doc.text('Part I: Income', 14, 60);
    doc.setFontSize(10);

    doc.text('1. Gross receipts or sales', 14, 68);
    doc.text(`$${summary.income.toFixed(2)}`, 150, 68, { align: 'right' });

    doc.text('7. Gross Income', 14, 76);
    doc.text(`$${summary.income.toFixed(2)}`, 150, 76, { align: 'right' });

    // -- Part II: Expenses --
    doc.setFontSize(12);
    doc.text('Part II: Expenses', 14, 86);

    const expenseRows = summary.breakdown.map(item => [
        item.taxCode,
        item.taxLabel || item.category,
        `$${item.totalAmount.toFixed(2)}`,
        `${(item.deductionRate * 100).toFixed(0)}%`,
        `$${item.deductibleAmount.toFixed(2)}`
    ]);

    autoTable(doc, {
        startY: 90,
        head: [['Tax Line', 'Description', 'Total', 'Rate', 'Deductible']],
        body: expenseRows,
        foot: [['', 'Total Deductions', '', '', `$${summary.totalDeductions.toFixed(2)}`]],
        theme: 'striped',
        headStyles: { fillColor: [100, 100, 100] },
        footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' }
    });

    // -- Summary --
    const finalY = (doc as any).lastAutoTable.finalY || 150;

    doc.setFontSize(12);
    doc.text('Summary', 14, finalY + 15);
    doc.setFontSize(10);

    doc.text('Tentative Profit (Loss)', 14, finalY + 25);
    doc.text(`$${summary.netProfit.toFixed(2)}`, 150, finalY + 25, { align: 'right' });

    if (summary.netProfit < 0) {
        doc.setTextColor(255, 0, 0);
        doc.text('NET LOSS', 160, finalY + 25);
        doc.setTextColor(0, 0, 0);
    } else {
        doc.setTextColor(0, 128, 0);
        doc.text('NET PROFIT', 160, finalY + 25);
        doc.setTextColor(0, 0, 0);
    }

    // -- Footer --
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.text('Generated by Snapceit', 14, pageHeight - 10);
    doc.text(new Date().toLocaleString(), 150, pageHeight - 10);

    return doc.output('blob');
}
