version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "receipt-categorizer-stack"
region = "us-east-1"
confirm_changeset = false
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
parameter_overrides = [
    "ReceiptsTableName=receipts",
    "Environment=dev"
]
